In [ ]:
import numpy as np
print(np.__version__)
a = np.array([2,3,4]) #สร้างอาร์เรน์จากลิสต์
b = np.array(range(1,100)) #สร้างอาร์เรน์จาก Range
c = np.array((7,11,101,555)) #สร้างอาร์เรน์จาก ทูเพิล
d = np.array([x**2 for x in range(0,100)]) #สร้างอาร์เรน์จาก for 
print(d)

In [ ]:
import numpy as np
#สร้้างโดยชังก์ชันของ Numpy
# zeros(size) สร้าง ar โดยให้สมาชิกค่าเริ่มต้นคือ 0
# ones(size) สร้าง ar โดยให้สมาชิกค่าเริ่มต้นคือ ๅ
# full(size,value)สร้าง ar โดยให้สมาชิกเป็นค่าที่กำหนด value
# arange(star,stop,step)
# linspace(begin,end,size) 
# random.randint(low,hight,size)
# random.unfiform(low,hight,size)
# random.rand(size)
a = np.zeros(10)
b = np.ones(10)
c = np.full(5,8)
d = np.arange(0,100)
e = np.arange(0,100,5)
f = np.linspace(1,100,5)
g = np.random.randint(0,100,10)
h = np.random.uniform(1,101,10)
i = np.random.rand(10)
#การเข้าถึงอาร์เรย์
print(d[5])
print(d[5] + d[2])
print(d[-5])
# print(*d)
for value in d: print(value)
#การเข้าถึงช่วงๆ
print(d[5:])

In [ ]:
import numpy as np
d = np.arange(0,100)
print(d[0:15:2])
inx = [0,2,19,21,15]
# การเข้าถึงโดยใช้ ลิสต์
a = d[inx]
print(a)


In [ ]:
# อาร์เรย์ 2 มิติ
a2d = np.array([[1,2,3],[3,4,6]])
print(a2d)
a = np.zeros([3,2])
b = np.ones([3,2])
c = np.full([2,3],8)
d = np.arange(0,100)
e = np.arange(0,100,5)
f = np.linspace(1,100,5)
g = np.random.randint(0,100,[3,2])
h = np.random.uniform(1,101,[3,2])
i = np.random.rand(10,2)
print(g[2,1])


In [ ]:
# การคำนวนอาร์เรย์ อาร์เรย์ต้องมีขนาดเท่ากัน
print(d+d)
print(d+10)
print(d-d)
print(d*d)
print(d/d)
print(d**2)
print(d==d)
print(d>10)


In [148]:
# ฟังก์ชันที่น่าสนใจ
print(d.sum())
print(d.min())
print(d.max())
print(d.mean())

a1 = np.arange(1,11)
print(a1.reshape(2,5))

print(d.reshape(-1,4))
print(d.reshape(4,-1))




4950
0
99
49.5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]
 [64 65 66 67]
 [68 69 70 71]
 [72 73 74 75]
 [76 77 78 79]
 [80 81 82 83]
 [84 85 86 87]
 [88 89 90 91]
 [92 93 94 95]
 [96 97 98 99]]


import numpy as np
d = np.arange(0,100)
